version: 0.5.{build}
skip_tags: true
configuration: Release
os: Visual Studio 2017
platform: Any CPU
clone_depth: 2
test: off
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - choco install gitlink -y
before_build:
  - nuget restore
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
  - ps: Remove-Item packages\OpenCover* -include ("*.pdb", "*.sln", "*.csproj") -recurse
  - GitLink .\
after_test:
# This runs the tests with OpenCover and publishes the report to Coverall
    - ps: .\CreateCoverage.ps1
environment:
  COVERALLS_REPO_TOKEN:
    secure: Rbs5lhh1vnIkleZR7LR5bq/EdRst4drUHr78SBrNjxIDf/KhH9S4sAn7xF4Q/LrZ
build:
  project: Dapplo.Config.sln
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: false
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/